# matrix:
#   include:
#     - os: osx
#       language: objective-c
#       osx_image: xcode9.1
#       env:
#         - JOB_NAME=DEFAULT_IOS
#     - os: osx
#       language: objective-c
#       osx_image: xcode9.1
#       install: echo "PODSPEC install"
#       before_script: echo "PODSPEC before_script"
#       script: .travis/podspec/ci.sh
#       env:
#         - JOB_NAME=PODSPEC_IOS
#     - os: linux
#       language: android
#       jdk: oraclejdk8
#       sudo: required
#       android:
#         components:
#           - platform-tools
#           - tools
#           - build-tools-25.0.0
#           - build-tools-26.0.2
#           - android-21
#           - android-26
#           - sys-img-armeabi-v7a-android-21
#           - extra-android-m2repository
#           - extra-google-m2repository
#           - extra-google-google_play_services
#       env:
#         - JOB_NAME=ANDROID_5
#
# cache:
#   directories:
#     - $HOME/.nvm
#     - $HOME/.npm
#     - $HOME/.cocoapods
#     - $HOME/.gradle/caches/
#     - $HOME/.gradle/wrapper/
#
# before_install: . .travis/before-install.sh
# install: .travis/install.sh
# before_script: .travis/before-ci.sh
# before_cache: .travis/before-cache.sh
# script: .travis/ci.sh

language: node_js
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

script: yarn && yarn build

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: lifeomic/tipsi-stripe
    os: linux

notifications:
  email:
    recipients:
      - $NPM_EMAIL
    on_success: change
    on_failure: always
